name: Frontend CI

on:
  # push to main branch
  push:
    branches:
      - main
  # pull request to main branch
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    env:
      # 環境変数を無効にする
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         persist-credentials: false

      - name: Setup Node.js
        uses: npm/setup-node@v3
        with:
          version: '24.11.0'
          cache: 'npm' # npmのキャッシュを使用

      - name: Install dependencies
        run: npm ci # 依存関係をインストール
      
      - name: Run ESLint
        run: npm run lint # ESLintを実行
      
      - name: Run tests
        run: npm run test -- --ci --coverage # CI環境にてテストを実行

      - name: Build
        run: npm run build # ビルドを実行
